services:
  backend:
    build:
      context: ./LibraryBackend
    environment:
      - ASPNETCORE_URLS=http://+:5214
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/library.db
      - HostConnection__Url=http://localhost
      - HostConnection__Port=8080
    volumes:
      - db-data:/app/data

  frontend:
    build:
      context: ./LibraryFrontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  db-data:
